# Generated by Django 2.0 on 2017-12-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0003_auto_20171207_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
